ServerName localhost

<Directory /var/www/html/android_sample_api>
    AllowOverride All
    Options -Indexes
    Require all granted
</Directory>

<Directory /var/www/html/android_sample_api/uploads>
    <FilesMatch "\.(php|phar|phtml|cgi|pl)$">
        Require all denied
    </FilesMatch>
</Directory>

SetEnvIf Authorization "(.+)" HTTP_AUTHORIZATION=$1

LimitRequestBody 2097152
